"""Small host entry over existing kernels; no extra IR, agent or generation transport."""
from pathlib import Path
from .v5 import V5Kernel
from .v5_modules import read
from . import workspace


def compact(result: dict) -> dict:
    """Keep blockers/receipts intact; don't print a second copy of the task file."""
    view = dict(result)
    task = view.pop('task', None)
    if not isinstance(task, dict):
        return view
    if not view.get('task_file'):
        # Never discard the only available copy (for example a future V6 shape).
        return dict(result)
    view['task'] = {key: task[key] for key in
                    ('task_id', 'kind', 'stage', 'scope', 'expected_result') if key in task}
    if workspace.enabled(task.get('project') or {}):
        view['required_read_count'] = len(view.pop('required_reads', []))
    view['instruction'] = ('Read task_file and its required_reads. Author only this native result; '
                           'then use step --result. Hash-identical instructions may be reused '
                           'in the same context; changed hashes must be read again.')
    return view


def start(project, inputs, *, profile='lean', project_id='PROJECT', delivery='full',
          target=None, mode=None, production_target='none', verbose=False, control_minimum=0, craft_routing='auto', output_profile=None, creative_policy='automatic', reference_refinement=None, flow_account=None, editing_backend='jianying-headless'):
    if profile not in ('lean', 'audited'):
        raise ValueError('Unknown workflow profile')
    if craft_routing not in ('auto', 'off'):
        raise ValueError('Unknown craft routing mode')
    output_profile = output_profile or ('compact' if profile=='lean' else 'audit')
    if output_profile not in ('compact','audit'):raise ValueError('Unknown output profile')
    if profile=='audited' and output_profile=='compact':raise ValueError('Audited projects require audit evidence; choose --output-profile audit')
    reference_refinement=reference_refinement or ('google-flow-2k' if delivery=='full' else 'off')
    if reference_refinement not in ('google-flow-2k','off'):raise ValueError('Unknown reference refinement')
    if delivery=='text-only' and reference_refinement!='off':raise ValueError('Text-only delivery cannot require Flow media')
    if flow_account and reference_refinement=='off':raise ValueError('Flow account requires Flow refinement')
    options = dict(creative_policy=creative_policy, editing_backend=editing_backend, production_policy='verified-production/1.0',
                   flow_refinement={'policy':'google-flow-2k/1.0','account_hint':flow_account,'max_attempts':2} if reference_refinement!='off' else None,
                   project_id=project_id, delivery=delivery, target=target,
                   mode=mode, production_target=production_target, control_policy='adaptive-control/1.0',control_minimum=control_minimum,
                   craft_policy='craft-routing/1.0' if craft_routing == 'auto' else 'off')
    if profile == 'audited':
        from .v6_runtime import V6Runtime
        kernel = V6Runtime.initialize(project, inputs, **options)
    else:
        kernel = V5Kernel.initialize(project, inputs, workflow_profile='lean', output_policy=workspace.POLICY if output_profile=='compact' else None, **options)
    result = kernel.run()
    result['workflow_profile'] = profile
    result['review_policy'] = ('independent-per-stage' if profile == 'audited'
                               else 'current-agent-native-checks')
    return result if verbose else compact(result)


def step(project, *, result=None, verbose=False):
    config = read(Path(project).expanduser().resolve() / 'project.json')
    is_v6 = config.get('orchestration_protocol') == '6.0'
    if is_v6:
        if result is not None:
            raise ValueError('V6 requires agent-result and independent agent-review; step cannot bypass them')
        from .v6_runtime import V6Runtime
        kernel = V6Runtime(project)
    else:
        kernel = V5Kernel(project)
    receipt = kernel.submit(result) if result is not None else None
    if receipt is not None and receipt.get('status') not in ('ACCEPTED', 'ALREADY_ACCEPTED'):
        return receipt
    value = kernel.run()
    if receipt is not None:
        value['receipt'] = receipt
    if value.get('status') == 'DELIVERED':
        value['preproduction_complete'] = True
        value['video_complete'] = False
        if config.get('production_target') == 'video':
            value['next_action'] = ('Continue production freeze/execute-or-receive/accept/edit/whole-review/deliver. '
                                     'No video has been generated by step. Never relabel DELIVERED as VIDEO_DELIVERED.')
    return value if verbose else compact(value)
